### ISSUE TITLE
Doesnt work...

### ISSUE THREAD

**Issue by tigrazone** [grigoryoskin/vulkan-compute-ray-tracing#1] opened 2022-01-27 08:10 UTC
Hello!
I have 1050ti and i5, 16gb of memory and on Windows 10 I have only
C:\msys64\home\user\from-git\vk-compute\vulkan-compute-ray-tracing>vulkan.exe
available extensions:
        VK_KHR_device_group_creation
        VK_KHR_display
        VK_KHR_external_fence_capabilities
        VK_KHR_external_memory_capabilities
        VK_KHR_external_semaphore_capabilities
        VK_KHR_get_display_properties2
        VK_KHR_get_physical_device_properties2
        VK_KHR_get_surface_capabilities2
        VK_KHR_surface
        VK_KHR_surface_protected_capabilities
        VK_KHR_win32_surface
        VK_EXT_debug_report
        VK_EXT_debug_utils
        VK_EXT_direct_mode_display
        VK_EXT_swapchain_colorspace
        VK_NV_external_memory_capabilities
Swap chain supported formats: 3
Swap chain supported present modes: 4
mssa samples: 1
Swap chain supported formats: 3
Swap chain supported present modes: 4
Swap chain supported formats: 3
Swap chain supported present modes: 4
Swap chain image count: 3

And it's all - program finished without result.
How to fix it?
P.S. I understand russian language ;-)

**Comment by tigrazone** [comment] 2022-01-27 09:37
When I start it from mingw sh, I have
$ ./vulkan.exe
Segmentation fault

Window created and flickered and program fails

**Comment by tigrazone** [comment] 2022-01-27 09:52
I added debug output in app-context/VulkanSwapchein.cpp
```

    std::cout << "84\n";

    QueueFamilyIndices indices = VulkanGlobal::context.queueFamilyIndices;
    uint32_t queueFamilyIndices[] = {indices.graphicsFamily.value(),
                                        indices.presentFamily.value()};

    if (indices.graphicsFamily != indices.presentFamily) {
        createInfo.imageSharingMode = VK_SHARING_MODE_CONCURRENT;
        createInfo.queueFamilyIndexCount = 2;
        createInfo.pQueueFamilyIndices = queueFamilyIndices;
    } else {
        createInfo.imageSharingMode = VK_SHARING_MODE_EXCLUSIVE;
        createInfo.queueFamilyIndexCount = 0; // Optional
        createInfo.pQueueFamilyIndices = nullptr; // Optional
    }
    createInfo.preTransform = swapChainSupport.capabilities.currentTransform;
    createInfo.compositeAlpha = VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR;
    createInfo.presentMode = presentMode;
    createInfo.clipped = VK_TRUE;
    createInfo.oldSwapchain = VK_NULL_HANDLE;

    std::cout << "105\n";

    if (vkCreateSwapchainKHR(VulkanGlobal::context.device, &createInfo, nullptr, &swapChain) != VK_SUCCESS) {
        throw std::runtime_error("failed to create swap chain!");
    }

    vkGetSwapchainImagesKHR(VulkanGlobal::context.device, swapChain, &imageCount, nullptr);
    swapChainImages.resize(imageCount);
    vkGetSwapchainImagesKHR(VulkanGlobal::context.device, swapChain, &imageCount, swapChainImages.data());
    swapChainImageFormat = surfaceFormat.format;
    swapChainExtent = extent;

    std::cout << "117\n";
```
    
and I have 
Swap chain image count: 3
84
105
I.e. program fails on
```
if (vkCreateSwapchainKHR(VulkanGlobal::context.device, &createInfo, nullptr, &swapChain) != VK_SUCCESS) {
        throw std::runtime_error("failed to create swap chain!");
    }
```

**Comment by grigoryoskin** [comment] 2022-01-30 12:21
Hi! Thank you for trying it out!
I think that if swapchain was the problem, we would get the error message. 
Maaaybe the problem is in the physical device? 
Currently I loop through devices and chose the first one available here: https://github.com/grigoryoskin/vulkan-compute-ray-tracing/blob/master/src/app-context/VulkanApplicationContext.cpp#L244-L252

If you have both integrated and separate gpu, it might be choosing integrated one by default.
Could you comment out `break;` [here](https://github.com/grigoryoskin/vulkan-compute-ray-tracing/blob/master/src/app-context/VulkanApplicationContext.cpp#L250) and see if it works?

**Comment by grigoryoskin** [comment] 2022-01-30 12:23
By the way, I used [this project](https://github.com/grigoryoskin/vulkan-project-starter) as a base. It doesn't have any compute or ray tracing stuff. Could you see if it works on your machine?

**Comment by tigrazone** [comment] 2022-01-30 20:31
> comment out `break;` [here](https://github.com/grigoryoskin/vulkan-compute-ray-tracing/blob/master/src/app-context/VulkanApplicationContext.cpp#L250) and see if it works?
It not helped me. Stoped on same place

vulkan-project-starter doesnt work for me and stoped on same place

**Comment by tigrazone** [comment] 2022-01-30 21:15
I try similar project https://github.com/GraphicsProgramming/RVPT
And it works ok for me.
Maybe sources of it helps you to make your project works ok

**Comment by grigoryoskin** [comment] 2022-01-31 02:33
It looks like they use 'vk-bootstrap' for device and swapchain, whereas I use barebones vulkan code.
I'll try switching to vk-bootstrap too.

**Comment by grigoryoskin** [comment] 2022-01-31 14:54
@tigrazone I added vk-bootstrap, so it might work better now.
It's in a new submodule, so you might need to re clone if submodule update doesn't work.

**Comment by tigrazone** [comment] 2022-02-01 08:10
Now renderer is started and show rendering times but I have black window.
After loading of mesh model I printf filename and count of triangles.
Built with mingw and started on windows 10
![image](https://user-images.githubusercontent.com/3808839/151933108-a0f2b2b1-9c0d-4ca2-b9f3-a395f049d069.png)

**Comment by tigrazone** [comment] 2022-02-01 08:27
one more issue. when I resize window, program fails with messages
[ERROR: Validation]
Validation Error: [ VUID-vkDestroyCommandPool-commandPool-00041 ] Object 0: handle = 0x16bdb1cd800, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xad474cda | Attempt to destroy command pool with VkCommandBuffer 0x16bdb1cd800[] which is in use. The Vulkan spec states: All VkCommandBuffer objects allocated from commandPool must not be in the pending state (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkDestroyCommandPool-commandPool-00041)
[ERROR: Validation]
Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x16bd5e66d60, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0x59ffe0000000003d, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x16bd5e66d60[], VkSemaphore 0x59ffe0000000003d[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)
[ERROR: Validation]
Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x16bd5e66d60, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0x9f9b41000000003c, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x16bd5e66d60[], VkSemaphore 0x9f9b41000000003c[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)
[ERROR: Validation]
Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x16bd5e66d60, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0x944a2c0000000039, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x16bd5e66d60[], VkSemaphore 0x944a2c0000000039[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)
[ERROR: Validation]
Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x16bd5e66d60, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0x210d07000000003a, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x16bd5e66d60[], VkSemaphore 0x210d07000000003a[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)
[ERROR: Validation]
Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x16bd5e66d60, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0x5eb05e000000003b, type = VK_OBJECT_TYPE_FENCE; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x16bd5e66d60[], VkFence 0x5eb05e000000003b[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)
[ERROR: Validation]
Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x16bd5e66d60, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0x5c5283000000003e, type = VK_OBJECT_TYPE_FENCE; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x16bd5e66d60[], VkFence 0x5c5283000000003e[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)

I understand, you dont implement window resize yet

**Comment by grigoryoskin** [comment] 2022-02-01 09:16
Hmm interesting.
0.4 ms/frame is too fast, it looks like cpp side doesn't wait for gpu and just skips to the next frame... So the problem might be with fences or semaphores. 

I'll try to reproduce this problem on a different machine and let you know.

**Comment by tigrazone** [comment] 2022-02-01 09:36
Maybe not processed lights?

**Comment by tigrazone** [comment] 2022-02-01 10:05
Tested on ubuntu linux on same computer and have this
![Screenshot from 2022-02-01 12-02-33](https://user-images.githubusercontent.com/3808839/151948787-3d640089-8e5c-448c-93cd-6aab0336c77f.png)
Also I have compile errors with filename Mesh.h and mesh.h and on sources folder is mesh.h, mesh.cpp, not Mesh.cpp and Mesh.h
Changed it to mesh.h and compiled ok

**Comment by grigoryoskin** [comment] 2022-02-01 10:25
I couldn't reproduce yet, but 100 ms/frame looks more like what it should be. 
Black might be either clear screen or black background from the shader.
Could you change the shader here and run compile.sh?
 https://github.com/grigoryoskin/vulkan-compute-ray-tracing/blob/master/resources/shaders/source/ray-trace-compute.comp#L326-L328
like this:
```
//final_color *= 0.0;
float t = 0.5*(unit_direction.y + 1.0);
final_color *= (1.0-t)*vec3(1.0, 1.0, 1.0) + t*vec3(1.0, 0.1, 1.0);
```
This will change the background skybox color.
If the screen remains black, this means there's a problem with vulkan somewhere. If the color changes, the problem is closer to the surface.

**Comment by tigrazone** [comment] 2022-02-01 10:50
![Screenshot from 2022-02-01 12-50-07](https://user-images.githubusercontent.com/3808839/151955321-246bd5e6-34db-4e7e-82d3-e83ff3f51e6b.png)
after changing of shader code

**Comment by grigoryoskin** [comment] 2022-02-01 11:01
This means that everything works except for geometry. By default the camera points at the scene so it should be visible from the start...
Did you try moving the camera (WASD and up/down keys)?
There's one more shader that does simplified scattering and ignores lights. You can try activating it here:
https://github.com/grigoryoskin/vulkan-compute-ray-tracing/blob/master/src/main.cpp#L123-L125

**Comment by tigrazone** [comment] 2022-02-01 11:08
When I push WASD nothing is changed. Only pink gradient.
Your projects seems unfinished and I want to get images from README

**Comment by tigrazone** [comment] 2022-02-01 18:57
One more question.
Is your path tracer use accumulated and final image in int or float rgb?
I want to get and use image in float format for make tone mapping and save as HDR/EXR

**Comment by grigoryoskin** [comment] 2022-02-02 09:56
I don't have time right now to install linux, but I ran on another Mac and got a flickering screen. 
There were two possible problems:
1) I was reading and writing to the same texture, so I added a separate accumulation texture. This solved flickering. 
2) I was getting buffer length in shader through `.length()`. So, I hardcoded buffer lengths into UBO. Maybe when you iterated through triangles you were getting 0 for `triangles.length()` and saw only the background.
I pushed the fixes so please check them out.  

> Is your path tracer use accumulated and final image in int or float rgb?

All textures are r8g8b8_unorm. You can't save it because it's only for display on gpu.

**Comment by grigoryoskin** [comment] 2022-02-02 09:59
Now that I think about it, just adding std430 to buffer declarations should have worked for `.length()`?

**Comment by tigrazone** [comment] 2022-02-02 10:10
About float values for images I mean output and accumulation image. For save result of rendering in hdr/exr or tonemapped png, jpg which is 8-bit uint

**Comment by tigrazone** [comment] 2022-02-02 10:52
I see only black window

**Comment by grigoryoskin** [comment] 2022-02-02 12:12
Then, I give up. I fixed every bug I could find and I can't reproduce this error.

**Comment by tigrazone** [comment] 2022-02-02 12:38
I dont have mac and I check updated in Ubuntu linux and windows 10 I have black window. 
Maybe check on windows/linux?

**Closed as completed** 2024-12-01 14:07 UTC
